### ISSUE TITLE
I can't publish hmap_100 design to Hyrax/THREDDS.

### ISSUE THREAD

**Issue by hyoklee** [HDFGroup/hpd-ws#14]
The design is pretty big and server returns 503 error:

```
hpdws.update_design() failed for hmap.100(503)
hmap_100
hpdws.publish():503
<!DOCTYPE html>
    <html>
    <head>
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <style type="text/css">
        html, body, iframe { margin: 0; padding: 0; height: 100%; }
        iframe { display: block; width: 100%; border: none; }
      </style>
    <title>Application Error</title>
    </head>
    <body>
      <iframe src="//s3.amazonaws.com/heroku_pages/error.html">
        <p>Application Error</p>
      </iframe>
    </body>
    </html>
```

**Comment by hyoklee** [comment]
I can't download it as HDF5 file either.

**Comment by ajelenak-thg** [comment]
Producing an HDF5 file took 47.3 seconds on my laptop. The hard limit for timing out requests is 30 seconds. Either we need to set up a job queue for these kind of requests or datasets should have their dims set to zeros so that no time is spent writing fill values into them.

**Comment by hyoklee** [comment]
I don't know why it takes so long for server to process. Importing also took more than 10 minutes. Is the hard limit set by Heroku?

**Comment by hyoklee** [comment]
How did you create HDF5 file on your laptop? My h5serv/util/jsontoh5 file throws an error.

**Comment by ajelenak-thg** [comment]
> How did you create HDF5 file on your laptop?

By running PD server on it.

> See HDFGroup/h5serv#42

Yes, I know. I fixed those in the PD server code.

**Comment by hyoklee** [comment]
Big design can be handled by server now via hdf5db.py optimization.
