### ISSUE TITLE
Typo in installation document?

### ISSUE THREAD

**Issue by hyoklee** [HDFGroup/hpd-ws#17]
http://hpd-ws.readthedocs.org/en/latest/install.html#requirements

```
psql $DATABASE_URL -f tools/create.sql
```

I can't locate tools/. I can't locate setup.sql either.

**Comment by ajelenak-thg** [comment]
There's a ``tools`` directory in the ``develop`` branch.

**Comment by hyoklee** [comment]
Why don't you push it to master?
