### ISSUE TITLE
Remove port numbers from OPeNDAP and THREDDS url return values.

### ISSUE THREAD

**Issue by hyoklee** [HDFGroup/hpd-ws#20]
Servers are migrated to port 80 which doesn't require port number.

**Comment by ajelenak-thg** [comment]
Did this 3 days ago but forgot to push that version. Try now.

**Comment by hyoklee** [comment]
Thanks, I can see it fixed.

**Comment by hyoklee** [comment]
Oops, revert the change. I think new users still use old version. My client is not out yet.

**Comment by ajelenak-thg** [comment]
Okay, reverted.
