### ISSUE TITLE
MATLAB code can't be compiled for compound dataset.

### ISSUE THREAD

**Issue by hyoklee** [HDFGroup/hpd-ws#28]
It seems that compound field's type information is passed through as is when array is used for field. 

The error message:
```
Error: File: /mnt/scr1/hyoklee/test.m Line: 736 Column: 29
Unexpected MATLAB expression.
 
>> 
```

The offending line.
```
field_tid(2) = H5T.copy('{u'class': u'H5T_FLOAT', u'base': u'H5T_IEEE_F32LE'}');
```

**Comment by ajelenak-thg** [comment]
Do you know a design I could use to test this?

**Comment by hyoklee** [comment]
Test alek-test-joe. I can’t even export as MATLAB code.

**Comment by ajelenak-thg** [comment]
> Test alek-test-joe. I can’t even export as MATLAB code.

It works now. And even produces a valid h5 file. :-) Todo: array compound members.

**Comment by hyoklee** [comment]
Awesome!

**Comment by ajelenak-thg** [comment]
Tested also with 123compound design:

```
HDF5 "123compound__HEAD__template.h5" {
GROUP "/" {
   DATASET "Sensor" {
      DATATYPE  H5T_COMPOUND {
         H5T_IEEE_F64LE "Time";
         H5T_ARRAY { [4] H5T_IEEE_F32LE } "Concentration";
         H5T_ARRAY { [8] H5T_STD_I8LE } "Species";
      }
      DATASPACE  SIMPLE { ( 15 ) / ( 15 ) }
   }
}
}
```

I think this issue can be considered fixed. Will close it.
