### ISSUE TITLE
Server can't move compound dataset from one group to another.

### ISSUE THREAD

**Issue by hyoklee** [HDFGroup/hpd-ws#29]
It doesn't return any error during the move but if I open the design again, it throws 500 error.

**Comment by ajelenak-thg** [comment]
I see some 409 responses in the log from the /movecontroller around the 500 responses that you mention. Don't know if they are related.

**Comment by hyoklee** [comment]
No. 409 Error occurs when I try to move it again. The first response is silent with no error message.

**Comment by ajelenak-thg** [comment]
I think this is fixed now?

**Comment by hyoklee** [comment]
I’m not 100% sure yet. Leave it open. I’ll close it after more testing.

**Comment by hyoklee** [comment]
I tested it with new HDFGroup/hpd#25 client and it worked.
