### ISSUE TITLE
What's the project creation policy when first names are same?

### ISSUE THREAD

**Issue by hyoklee** [HDFGroup/hpd-ws#35]
If a new user called 'Joe Kim' signs up for HPD, what will be his personal project name if project name 'Joe' is already taken? Does sever allow duplicate project name (i.e., can it distinguish Joe for 'Joe Lee' and another Joe for 'Joe Kim')?

**Comment by ajelenak-thg** [comment]
Lately I've been assigning full user names for their personal projects. First names for projects are only for special people. ;-)

Currently, project names are required to be unique across the database but it is not necessary. Each project has an ID assigned which is used for all db queries.

**Comment by hyoklee** [comment]
So do you use JoeKim or KimJoe? I'm in the middle of updating setup section of document and I'd like to specify it exactly.

**Comment by ajelenak-thg** [comment]
<first name> <last name>

**Comment by hyoklee** [comment]
Why doesn't commit message close issue automatically?
