### ISSUE TITLE
Size must be positive error?

### ISSUE THREAD

**Issue by hyoklee** [HDFGroup/hpd-ws#36]
I can't publish 'Sandbox/alek-test-joe' design. I updated the design and server returns "500: Size must be positive error" when I publish it.  I don't understand why.

**Comment by ajelenak-thg** [comment]
My first guess: a compound dataset ``PROFILE`` has a string field named ``whynot`` with zero length.

**Comment by hyoklee** [comment]
I specified size for the string field and now I get 'invalid type' error. 

```
[Errno 22] Unable to create type: Type Error: invalid type
```

What could be wrong?

**Comment by ajelenak-thg** [comment]
The ``whynot``'s base string datatype is not declared correctly. Missing ``charSet``, ``length``, etc.

```json
{
    "type": {
        "dims": [
            10
        ],
        "base": {
            "base": "H5T_STRING",
            "class": "H5T_STRING"
        },
        "class": "H5T_ARRAY"
    },
    "name": "whynot"
}
```

**Comment by hyoklee** [comment]
I can see  your unpublished branch "mv-compound" on hpd. Does it fix this problem? I don't remember whether it was merged to develop branch or not.

**Comment by ajelenak-thg** [comment]
It was merged two weeks ago. Where do you see it? It is not in the GitHub repo. Can you see it after running ``git fetch origin`` in your local repo?

**Comment by hyoklee** [comment]
I can see it through local GitHub client only, not GitHub.com repo.

**Comment by ajelenak-thg** [comment]
Even after executing ``git fetch origin``? This command should bring your local view of the GitHub repo into sync thus removing ``mv-compound`` branch.

As for your question whether that branch fixes this issue -- no. Did you fix the ``whynot``'s string datatype definition?

**Comment by hyoklee** [comment]
No, I did not fix it. I wanted to check with you first before I issue a new ticket to add string datatype compound field support. I'll try git fetch origin later after verifying everything is merged properly from mv-compound branch. Thanks for the tip.
