### ISSUE TITLE
Does generated Python code (exported from server) work for  Python 3.0?

### ISSUE THREAD

**Issue by hyoklee** [HDFGroup/hpd-ws#42]
Or is the Python code only for 2.7?
Which Python versions have you tested so far with generated codes?
Also, what version of h5py was generated code tested?

**Comment by jreadey** [comment]
It's only for 2.7.
We can look into support 3.x, but I'd wait to see if there is any demand for it.

The h5py version is 2.5.

**Comment by hyoklee** [comment]
Thanks. I'll update user guide accordingly.
