### ISSUE TITLE
Automatically set up account for authenticated new user

### ISSUE THREAD

**Issue by ajelenak-thg** [HDFGroup/hpd-ws#43]
If an authenticated user does not yet have an HPD account:

1. Create a new user account from the information obtained from authentication.
1. Send an email notification to the user about the new account.
1. Send an email to HPD admin about the new user.

**Comment by hyoklee** [comment]
+1 for this enhancement.

**Comment by hyoklee** [comment]
If you're going to set up mail system on HPD Server, please consider notification of shared design change by email in the future.

**Comment by ajelenak-thg** [comment]
Done. fc353e1a
