### ISSUE TITLE
Using iter as argument?

### ISSUE THREAD

**Issue by hyoklee** [HDFGroup/hpd-ws#46]
In util.py, I noticed that  [iter] (https://docs.python.org/2/library/functions.html#iter) built-in function name was used as an argument.

```
def value_check(iter, cond):
```
Is it required to use "iter"?
How about changing it to non built-in function name such as val_list?

**Comment by ajelenak-thg** [comment]
> Is it required to use "iter"?

No.

> How about changing it to non built-in function name such as val_list?

I will change it to `iter_`.

**Comment by ajelenak-thg** [comment]
Fixed. 14af80789e353065811791beef7ff8247dad9464
