### ISSUE TITLE
Chmod go+r published data for Hyrax.

### ISSUE THREAD

**Issue by hyoklee** [HDFGroup/hpd-ws#5]
Published data is only readable by user. Please change permission during file creation so that it can be readable by group and others so that Hyrax can access it properly. 

```
-rw------- 1 ec2-user ec2-user  15232 Mar  9 14:16 test6.h5
```

**Comment by ajelenak-thg** [comment]
Done: 119a4780

**Comment by hyoklee** [comment]
It still produces user read-only file at HPD Online. Add –p for scp argument.

**Comment by ajelenak-thg** [comment]
Try now. It copied correctly from my Mac without the `-p` option.

**Comment by hdfeos** [comment]
Yeah, it works! Close the ticket.
