### ISSUE TITLE
Please change data.hdfgroup.org to 54.174.38.12.

### ISSUE THREAD

**Issue by hyoklee** [HDFGroup/hpd-ws#51]
Webbrowsers redirect http traffic to https. It seems that using IP address can bypass it.

http://stackoverflow.com/questions/25901602/http-strict-transport-security-not-respected-for-ip-addresses

**Comment by ajelenak-thg** [comment]
Is this enough? cce4aa49cd07776a2adbe000113be21ca21b3ae2

**Comment by hyoklee** [comment]
Thanks, it's working well now.
