### ISSUE TITLE
Support H5T_VLEN and H5T_COMPOUND type attributes.

### ISSUE THREAD

**Issue by hyoklee** [HDFGroup/hpd-ws#7]
I get the following error messages when I tried exotic attribute types used in dimension scales. 

```
response={"message": "H5T_VLEN: HDF5 datatype class is not supported.", "link": [{"rel": "attributes", "title": "Object attributes", "href": "https://hpd-ws.herokuapp.com/entity/ecbde449-8e7f-4ea7-9b90-1f8776def81f/groups/ecbde449-8e7f-4ea7-9b90-1f8776def81f/attributes"}, {"rel": "entity", "title": "Entity", "href": "https://hpd-ws.herokuapp.com/entity/ecbde449-8e7f-4ea7-9b90-1f8776def81f"}, {"rel": "object", "title": "Object", "href": "https://hpd-ws.herokuapp.com/entity/ecbde449-8e7f-4ea7-9b90-1f8776def81f/groups/ecbde449-8e7f-4ea7-9b90-1f8776def81f"}]}


response={"message": "H5T_COMPOUND: HDF5 datatype class is not supported.", "link": [{"rel": "attributes", "title": "Object attributes", "href": "https://hpd-ws.herokuapp.com/entity/ecbde449-8e7f-4ea7-9b90-1f8776def81f/groups/ecbde449-8e7f-4ea7-9b90-1f8776def81f/attributes"}, {"rel": "entity", "title": "Entity", "href": "https://hpd-ws.herokuapp.com/entity/ecbde449-8e7f-4ea7-9b90-1f8776def81f"}, {"rel": "object", "title": "Object", "href": "https://hpd-ws.herokuapp.com/entity/ecbde449-8e7f-4ea7-9b90-1f8776def81f/groups/ecbde449-8e7f-4ea7-9b90-1f8776def81f"}]}
```

**Comment by ajelenak-thg** [comment]
Try now. There will be no input validation for these two datatypes.

**Comment by hyoklee** [comment]
It doesn't throw error any more but I hope you can validate inputs.

**Comment by ajelenak-thg** [comment]
> It doesn't throw error any more but I hope you can validate inputs.

What kind of validation you have in mind? Compounds can contain pretty much anything so a generic validation is not easy.

**Comment by hyoklee** [comment]
You can check if datasets with matching uuid values exist in DB.

**Comment by ajelenak-thg** [comment]
Two issues here:

1. The validation you want is not related to these two datatypes but to several dataset attributes related to dimension scales.
2. This kind of validation is dependent on the order of dataset creation. Probably doable when manually editing designs but not sure if it would work when importing them.
