### ISSUE TITLE
Send different status code other than 200 when user is unknown.

### ISSUE THREAD

**Issue by hyoklee** [HDFGroup/hpd-ws#8]
When I try [1], I occasionally get the following error message:
```
{"message": "User unknown. Please log in.", "link": [{"href": "https://hpd-ws.herokuapp.com/login/eosdis-urs?next=%2Fproject%2FSandbox", "title": "EOSDIS URS", "rel": "authentication"}, {"href": "https://hpd-ws.herokuapp.com/login/mockauth?next=%2Fproject%2FSandbox", "title": "Mock", "rel": "authentication"}]}
```
I hope server can send status code other than 200 to distinguish success and failure. 

[1] http://hpd-ws.readthedocs.org/en/latest/api.html#information-about-a-project

**Comment by ajelenak-thg** [comment]
This case is one of those where there is no a single RESTful best practice suggested. I opted for how Google us currently handling this: redirect (status code: 302) to a login page (200). Thinking about this now, that approach seems more appropriate for web browsers, not for REST API. Hence, the response is changed to: redirect (302) to a login page (`401 Unauthorized`). Done: 7d5ddce4
