### ISSUE TITLE
Clean up __ANONYMOUS__ object automatically.

### ISSUE THREAD

**Issue by hyoklee** [HDFGroup/hpd-ws#9]
When a new dataset with duplicate name is created and attached to the same group, __ANONYMOUS__ is created first and  attached to the group. During attachment, it fails because it has same name. If client doesn't delete the object explicitly, the __ANONYMOUS__ dataset will remain in the server. I hope server can delete such object automatically when a user tries to attach newly created object to the group.

**Comment by ajelenak-thg** [comment]
Why should the server delete the anonymous object? Perhaps the client wants to use a different name since the original one is not available. I think it is the client's role to delete that ANONYMOUS object if it does not have any need for it anymore.

**Comment by hyoklee** [comment]
I'm asking server to delete "when ANONYMOUS is attached to the group where same name exists" because it indicates that user has made a mistake of creating a dataset that already exists. It will reduce the network traffic of sending "DELETE" request.

Also, user will be surprised when he opens a design with __ANONYMOUS__ object in it because  he has never created_a dataset called "_ANONYMOUS__ ."

**Comment by ajelenak-thg** [comment]
> it indicates that user has made a mistake of creating a dataset that already exists. It will reduce the network traffic of sending "DELETE" request.

The network traffic is ridiculously small. The client created an anonymous object. Then it created a hard link. The second request failed because the name of that hard link was already used. Why would the server now assume the anonymous object should be deleted? The server does not read the client's mind.

> Also, user will be surprised when he opens a design with ANONYMOUS object in it because he has never created_a dataset called "ANONYMOUS ."

The user will not be surprised because the client will have deleted that anonymous object if it has no use for it anymore. Alternatively, you can use create-and-link request that avoids the two-step process.

**Comment by hyoklee** [comment]
No matter how small, traffic is traffic and if you multiply it by million users, it is $$$ in cloud apps. We need to optimize as much as possible in terms of storage and network usage in cloud apps. 

The server should be smart enough to figure it out that __ANONYMOUS__ is garbage because it is constructed by the server, not client. 

Create-and-link request sounds good. Is it documented? I can't find service endpoints for it from readthedocs.org.
